/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.time.LocalDate;
import javax.swing.JPanel;


/**
 *
 * @author joaco
 */
public class GestionDeTurnos extends javax.swing.JFrame {

    /**
     * Creates new form GestionDeTurnos
     */
    public GestionDeTurnos() {
        initComponents();
        initContent();
        initModificar();
        setDate();
    }
    public void initContent(){
          setJpanel(new Alta());
    }
        public void initModificar(){
        Modificar mod= new Modificar();
        mod.setSize(750,600);
        mod.setLocation(0, 0);
        
        content.removeAll();
        content.add(mod,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
       public static void setJpanel(JPanel panel){
        panel.setSize(750,600);
        panel.setLocation(0, 0);
        content.removeAll();
        content.add(panel,BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
        private void setDate(){
        LocalDate now= LocalDate.now();
        int year = now.getYear();
        int day =now.getDayOfMonth();
        int month = now.getMonthValue();
        String meses[]= {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Novimebre","Diciembre"};
        dateText.setText("Hoy es "+day+" de "+meses[month-1]+" de "+year);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGestTurno = new javax.swing.JPanel();
        lateralGestiTurn = new javax.swing.JPanel();
        BtnAlta = new javax.swing.JButton();
        btnEditarEliminar = new javax.swing.JButton();
        btnIcon2 = new javax.swing.JButton();
        FrontalGestiTurn = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 657));

        panelGestTurno.setMinimumSize(new java.awt.Dimension(1000, 800));
        panelGestTurno.setPreferredSize(new java.awt.Dimension(1000, 800));

        lateralGestiTurn.setBackground(new java.awt.Color(0, 102, 102));

        BtnAlta.setBackground(new java.awt.Color(0, 179, 184));
        BtnAlta.setForeground(new java.awt.Color(255, 255, 255));
        BtnAlta.setText("ALTA DE TURNO");
        BtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAltaActionPerformed(evt);
            }
        });

        btnEditarEliminar.setBackground(new java.awt.Color(0, 179, 184));
        btnEditarEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEliminar.setText("MODIFICAR/ELIMINAR TURNO");
        btnEditarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEliminarActionPerformed(evt);
            }
        });

        btnIcon2.setBackground(new java.awt.Color(0, 0, 0));
        btnIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ICONODE MEDICINA.png"))); // NOI18N
        btnIcon2.setBorderPainted(false);
        btnIcon2.setContentAreaFilled(false);
        btnIcon2.setDefaultCapable(false);
        btnIcon2.setFocusPainted(false);
        btnIcon2.setFocusable(false);
        btnIcon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIcon2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lateralGestiTurnLayout = new javax.swing.GroupLayout(lateralGestiTurn);
        lateralGestiTurn.setLayout(lateralGestiTurnLayout);
        lateralGestiTurnLayout.setHorizontalGroup(
            lateralGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralGestiTurnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lateralGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lateralGestiTurnLayout.createSequentialGroup()
                        .addGroup(lateralGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditarEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68))
                    .addGroup(lateralGestiTurnLayout.createSequentialGroup()
                        .addComponent(btnIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        lateralGestiTurnLayout.setVerticalGroup(
            lateralGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralGestiTurnLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(BtnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(487, Short.MAX_VALUE))
        );

        FrontalGestiTurn.setBackground(new java.awt.Color(0, 153, 153));

        dateText.setBackground(new java.awt.Color(255, 255, 255));
        dateText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {dayname} {day} de  {month} de {year}");

        javax.swing.GroupLayout FrontalGestiTurnLayout = new javax.swing.GroupLayout(FrontalGestiTurn);
        FrontalGestiTurn.setLayout(FrontalGestiTurnLayout);
        FrontalGestiTurnLayout.setHorizontalGroup(
            FrontalGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontalGestiTurnLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        FrontalGestiTurnLayout.setVerticalGroup(
            FrontalGestiTurnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrontalGestiTurnLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.lightGray));
        content.setForeground(new java.awt.Color(102, 102, 102));
        content.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        content.setMinimumSize(new java.awt.Dimension(800, 478));
        content.setName(""); // NOI18N
        content.setPreferredSize(new java.awt.Dimension(800, 478));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelGestTurnoLayout = new javax.swing.GroupLayout(panelGestTurno);
        panelGestTurno.setLayout(panelGestTurnoLayout);
        panelGestTurnoLayout.setHorizontalGroup(
            panelGestTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestTurnoLayout.createSequentialGroup()
                .addComponent(lateralGestiTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGestTurnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(FrontalGestiTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelGestTurnoLayout.setVerticalGroup(
            panelGestTurnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestTurnoLayout.createSequentialGroup()
                .addComponent(FrontalGestiTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
            .addComponent(lateralGestiTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lateralGestiTurn.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelGestTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGestTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAltaActionPerformed
            setJpanel(new Alta());
    }//GEN-LAST:event_BtnAltaActionPerformed

    private void btnEditarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEliminarActionPerformed
            setJpanel(new Modificar());
    }//GEN-LAST:event_btnEditarEliminarActionPerformed

    private void btnIcon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIcon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIcon2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDeTurnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDeTurnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAlta;
    private javax.swing.JPanel FrontalGestiTurn;
    private javax.swing.JButton btnEditarEliminar;
    private javax.swing.JButton btnIcon2;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel lateralGestiTurn;
    private javax.swing.JPanel panelGestTurno;
    // End of variables declaration//GEN-END:variables
}
